language: node_js

node_js:
  - "0.12"

env:
  - TESTING: true

before_install:
  - npm install -g gulp

before_script:
  - mysql -e 'create database myapp_test;'
  - node server/tasks/buildScrape.js

script:
  - gulp travis

